// This is a parser for AVS Syslog Firewall logs
AVSSyslog
| where AppName == "FIREWALL"
| parse Message with timestamp " " VIFId " " Source " " Id " " INETType " " Reason " " Action " " RuleName "/" RuleId " " Direction " " PacketSize " " Protocol " " *
| extend SourceIp = iff(Message contains "PROTO", extract(@".+PROTO\s\d\s([0-9\.]+)->.+",1,Message), extract(@".+\s([a-z0-9\.:]+)/\d+.+",1,Message))
| extend SourcePort = iff(Message contains "PROTO","",extract(@".+\s[a-z0-9\.:]+/(\d+)",1,Message))
| extend DestinationIp = extract(@".+->([0-9a-z\.:]+)",1,Message)
| extend DestinationPort = extract(@".+->[0-9a-z\.:]+/(\d+)",1,Message)
| extend TCPFlags = extract(@".+->[0-9a-z\.:]+/\d+\s(\w+)",1,Message)
